query {
  countryDestinations {
    id
    name
    cities {
      name
      slug
      toursCount {
        total
        tours
        activities
        transportation
      }
    }
    data {
      id
      keyword
      url
      order
    }
  }
}
